{
  "formatVersion": "1.1",
  "component": {
    "group": "com.amwal.amwal_pay",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 21175331,
          "sha512": "c296f36f4e74211d4c1efa06316dd8e49455b8b11962894f7b370c3d0ddb09098607ecfef8431bade9a28bb3346045332870e100fb2da059de83b8746afa56d4",
          "sha256": "87a9317698d7dae977a3c783ef8c5128507c21edea24378638dbc4231f52260e",
          "sha1": "9f5cd65c5c7f9ba8b0e45c6b0c9029043959e8e0",
          "md5": "1b9d902d101bbd0c1a3f11925b78a0c0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 21175331,
          "sha512": "c296f36f4e74211d4c1efa06316dd8e49455b8b11962894f7b370c3d0ddb09098607ecfef8431bade9a28bb3346045332870e100fb2da059de83b8746afa56d4",
          "sha256": "87a9317698d7dae977a3c783ef8c5128507c21edea24378638dbc4231f52260e",
          "sha1": "9f5cd65c5c7f9ba8b0e45c6b0c9029043959e8e0",
          "md5": "1b9d902d101bbd0c1a3f11925b78a0c0"
        }
      ]
    }
  ]
}
