{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 22326,
          "sha512": "36dd80de5da6da593ff0c772051c471bb8497401c4570269d1c7e75032319119e085dee8fb95d84e512a3162d4745abdc04d9e088695ef40487dca658b367121",
          "sha256": "efa8bb7470cb7f526d846b2cbdfd80be0aebc379725e4d5817fb0299a0821808",
          "sha1": "30c88844dfd9efb32949625d4cb58b0e2c8593c1",
          "md5": "da7790a92a284a79cfbf1389993c4317"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-1ac611c64eadbd93c5f5aba5494b8fc3b35ee952"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 22326,
          "sha512": "36dd80de5da6da593ff0c772051c471bb8497401c4570269d1c7e75032319119e085dee8fb95d84e512a3162d4745abdc04d9e088695ef40487dca658b367121",
          "sha256": "efa8bb7470cb7f526d846b2cbdfd80be0aebc379725e4d5817fb0299a0821808",
          "sha1": "30c88844dfd9efb32949625d4cb58b0e2c8593c1",
          "md5": "da7790a92a284a79cfbf1389993c4317"
        }
      ]
    }
  ]
}
