{
  "formatVersion": "1.1",
  "component": {
    "group": "fman.ge.smart_auth",
    "module": "smart_auth_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "smart_auth_profile-1.0.aar",
          "url": "smart_auth_profile-1.0.aar",
          "size": 37277,
          "sha512": "459897adbac6ce009d554cc25eec88d7f686e559c806681951895af007227ca13123cd2edbeea4b1b0096d98c67593c90c302d7a3504fa75eb837ca8721d683e",
          "sha256": "6c33914bf9a62fa49644a6287038e02bcfd4ffe25ace2c77054f283650cdcc56",
          "sha1": "fd94f482f883460c8e197a433ee59201ab4d7309",
          "md5": "8b66d6d3f26c0ae0d6c563beadfb87a9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "smart_auth_profile-1.0.aar",
          "url": "smart_auth_profile-1.0.aar",
          "size": 37277,
          "sha512": "459897adbac6ce009d554cc25eec88d7f686e559c806681951895af007227ca13123cd2edbeea4b1b0096d98c67593c90c302d7a3504fa75eb837ca8721d683e",
          "sha256": "6c33914bf9a62fa49644a6287038e02bcfd4ffe25ace2c77054f283650cdcc56",
          "sha1": "fd94f482f883460c8e197a433ee59201ab4d7309",
          "md5": "8b66d6d3f26c0ae0d6c563beadfb87a9"
        }
      ]
    }
  ]
}
